# (id, pause_before_s, texte affiché, texte prononcé ou None)
LINES = [
 ("hook1", 0.7, "Voici l'erreur que font la plupart des graphistes, des monteurs et des motion designers.", None),
 ("hook2", 0.3, "Ils pensent que leur talent suffit à vendre.", None),
 ("cause", 0.45, "Mais leurs clients ne les trouvent pas. Ils attendent un devis pendant des jours. Et ils ne savent jamais où en est leur commande.", None),
 ("result", 0.45, "Résultat : ils partent chez le concurrent. Même quand votre travail est meilleur.", None),
 ("reveal", 0.9, "La solution s'appelle Concept Pub.", "La solution s'appelle Concept Pube."),
 ("for", 0.25, "Un site vitrine haut de gamme, conçu pour les studios de création, les agences de communication et les boîtes de production.", None),
 ("look", 0.5, "Dès la première seconde, l'image impose le respect. Noir, ivoire et or : une direction artistique digne des grandes maisons.", None),
 ("scroll", 0.35, "Regardez : chaque section se révèle au défilement, avec des animations fluides, dignes d'une marque de luxe.", None),
 ("reel", 0.3, "Vos neuf métiers sont présentés avec clarté, et vos réalisations défilent comme au cinéma.", None),
 ("sells", 0.6, "Mais surtout, ce site ne se contente pas de montrer. Il vend.", None),
 ("devis1", 0.45, "Votre client choisit sa prestation, règle la durée, ajoute ses options…", None),
 ("devis2", 0.2, "et le prix se met à jour en direct, sous ses yeux.", None),
 ("devis3", 0.35, "Il valide, et sa commande est enregistrée. Sans un seul appel.", None),
 ("rdv", 0.45, "Il réserve lui-même son rendez-vous : le jour, l'heure, en visio ou au studio.", None),
 ("client1", 0.6, "Et voici l'atout qui fait toute la différence : l'espace client.", None),
 ("client2", 0.3, "Votre client se connecte, et retrouve toutes ses commandes au même endroit.", None),
 ("client3", 0.3, "Les projets en cours, avec leur avancement, étape par étape.", None),
 ("client4", 0.3, "Les commandes livrées, avec les fichiers prêts à télécharger.", None),
 ("client5", 0.3, "Et les devis à valider, en un seul clic.", None),
 ("client6", 0.45, "Plus de relances, plus de fichiers perdus : votre studio paraît aussi professionnel qu'une grande agence.", None),
 ("benef", 0.6, "Moins d'allers-retours. Plus de commandes. Une image irréprochable.", None),
 ("mobile", 0.5, "Le site s'adapte à tous les écrans, aussi élégant sur mobile que sur grand écran.", None),
 ("ds", 0.35, "Et il repose sur un design system complet : couleurs, typographies, composants. Votre logo, vos prestations, vos tarifs : tout se personnalise, sans repartir de zéro.", None),
 ("offer", 0.6, "Vous repartez avec le site, son système graphique, et ce film de présentation.", None),
 ("weeks", 0.3, "Des semaines de conception, déjà faites. Il ne reste qu'à y mettre votre nom.", None),
 ("sign", 0.8, "Concept Pub. L'image qui fait vendre.", "Concept Pube. L'image qui fait vendre."),
 ("cta", 0.3, "Réservez votre démonstration dès aujourd'hui.", None),
]
