import type { LevelDef } from "./types";

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: "Le Ruisseau",
    description: "Un petit fossé. Une simple poutre en bois devrait suffire pour laisser passer une charrette.",
    gapWidth: 260,
    anchorLeftY: 420,
    anchorRightY: 420,
    budget: 420,
    waves: [{ type: "cart", count: 1, gapMs: 0 }],
    unlockedMaterials: ["wood"],
    starBudgetBonus: [0.5, 0.75],
  },
  {
    id: 2,
    name: "La Route Marchande",
    description: "Deux charrettes vont suivre. Pensez à trianguler votre structure pour la stabiliser.",
    gapWidth: 320,
    anchorLeftY: 420,
    anchorRightY: 420,
    budget: 520,
    waves: [{ type: "cart", count: 2, gapMs: 1400 }],
    unlockedMaterials: ["wood"],
    starBudgetBonus: [0.5, 0.75],
  },
  {
    id: 3,
    name: "Le Ravin",
    description: "Une automobile bien plus lourde qu'une charrette va traverser. Le bois seul ne suffira peut-être plus.",
    gapWidth: 380,
    anchorLeftY: 400,
    anchorRightY: 440,
    budget: 700,
    waves: [
      { type: "cart", count: 1, gapMs: 0 },
      { type: "car", count: 1, gapMs: 1600 },
    ],
    unlockedMaterials: ["wood", "cable"],
    starBudgetBonus: [0.5, 0.7],
  },
  {
    id: 4,
    name: "La Gorge Rocheuse",
    description: "L'acier fait son apparition. Une structure en treillis répartira mieux les charges.",
    gapWidth: 440,
    anchorLeftY: 400,
    anchorRightY: 400,
    budget: 950,
    waves: [
      { type: "car", count: 2, gapMs: 1300 },
    ],
    unlockedMaterials: ["wood", "steel", "cable"],
    starBudgetBonus: [0.45, 0.7],
  },
  {
    id: 5,
    name: "Le Passage du Camionneur",
    description: "Un camion chargé pèse bien plus lourd. Renforcez le tablier et les appuis.",
    gapWidth: 480,
    anchorLeftY: 420,
    anchorRightY: 380,
    budget: 1150,
    waves: [
      { type: "car", count: 1, gapMs: 0 },
      { type: "truck", count: 1, gapMs: 1800 },
    ],
    unlockedMaterials: ["wood", "steel", "cable"],
    starBudgetBonus: [0.4, 0.65],
  },
  {
    id: 6,
    name: "Le Grand Canyon",
    description: "Une portée large exige des câbles en tension et une armature en acier bien pensée.",
    gapWidth: 560,
    anchorLeftY: 400,
    anchorRightY: 400,
    budget: 1450,
    waves: [
      { type: "truck", count: 2, gapMs: 2000 },
    ],
    unlockedMaterials: ["wood", "steel", "cable"],
    starBudgetBonus: [0.4, 0.65],
  },
  {
    id: 7,
    name: "La Route des Poids Lourds",
    description: "Un poids lourd va tester chaque assemblage. Aucune faiblesse ne sera pardonnée.",
    gapWidth: 620,
    anchorLeftY: 440,
    anchorRightY: 400,
    budget: 1750,
    waves: [
      { type: "truck", count: 1, gapMs: 0 },
      { type: "heavyTruck", count: 1, gapMs: 2200 },
    ],
    unlockedMaterials: ["wood", "steel", "cable"],
    starBudgetBonus: [0.35, 0.6],
  },
  {
    id: 8,
    name: "Le Défi du Transporteur",
    description: "Le niveau ultime : un convoi complet, terminé par un transporteur géant. Construisez pour durer.",
    gapWidth: 700,
    anchorLeftY: 420,
    anchorRightY: 420,
    budget: 2100,
    waves: [
      { type: "car", count: 2, gapMs: 1200 },
      { type: "heavyTruck", count: 1, gapMs: 2000 },
      { type: "hauler", count: 1, gapMs: 2600 },
    ],
    unlockedMaterials: ["wood", "steel", "cable"],
    starBudgetBonus: [0.3, 0.55],
  },
];

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}
