import type { VehicleDef, VehicleType } from "./types";

export const VEHICLES: Record<VehicleType, VehicleDef> = {
  cart: {
    type: "cart",
    label: "Charrette de marchand",
    weight: 55,
    width: 46,
    height: 22,
    wheelRadius: 10,
    color: "#7a4a2b",
    speed: 2.4,
  },
  car: {
    type: "car",
    label: "Automobile",
    weight: 95,
    width: 62,
    height: 26,
    wheelRadius: 12,
    color: "#c0392b",
    speed: 3.0,
  },
  truck: {
    type: "truck",
    label: "Camion chargé",
    weight: 210,
    width: 88,
    height: 34,
    wheelRadius: 14,
    color: "#2e6f9e",
    speed: 2.2,
  },
  heavyTruck: {
    type: "heavyTruck",
    label: "Poids lourd",
    weight: 380,
    width: 110,
    height: 40,
    wheelRadius: 16,
    color: "#3a5f3a",
    speed: 1.8,
  },
  hauler: {
    type: "hauler",
    label: "Transporteur géant",
    weight: 620,
    width: 140,
    height: 48,
    wheelRadius: 18,
    color: "#5b3a70",
    speed: 1.4,
  },
};
