// Lancer : node sites/livensya/robot-achat/tests/scenarios.js   (aucun appel réseau : tout est simulé)
const s = require('./simulateur');
const MIN = 60 * 1000, JOUR = 24 * 3600 * 1000;
let e, p, r;
const passage = (e, n = 1, pas = 5 * MIN) => { for (let i = 0; i < n; i++) { e.avancer(pas); e.api.envoyerEnAttente(); } };
const statut = e => String((s.ventes(e).slice(-1)[0] || [])[7] || '');

console.log('\n1. Vente valide (fiche au format réel, statut « settled ») : webhook, puis signal 5 s après');
e = s.charger(); e.fiches.SALEA1 = s.fiche('SALEA1');
s.post(e, s.webhook('SALEA1'));
s.verifier(s.purchases(e).length === 0, 'au webhook : rien envoyé, on attend le signal');
s.verifier(e.lecturesChariow.length === 1 && e.lecturesChariow[0].id === 'SALEA1', 'fiche Chariow relue une fois');
s.verifier(statut(e) === 'En attente du signal de la page', 'onglet Ventes : en attente');
e.avancer(5000); s.post(e, s.signal('SALEA1'));
p = s.purchases(e);
s.verifier(p.length === 1, '1 seul Purchase (' + p.length + ')');
const d = p[0] || { user_data: {}, custom_data: {} }, u = d.user_data;
s.verifier(d.event_id === 'SALEA1' && d.action_source === 'website', 'event_id = ID de la vente, action_source website');
s.verifier(d.event_time === Date.parse('2026-10-09T09:59:30Z') / 1000, 'event_time = heure de la vente (format .000000Z lu), en secondes');
s.verifier(d.event_source_url === 'https://livensya.emkbluediamond.online/?fbclid=IwAR0abc', 'event_source_url = page du signal');
s.verifier(d.custom_data.value === 3999 && d.custom_data.currency === 'XOF' && d.custom_data.content_ids[0] === 'prd_4bisyd7x', 'value 3999 (amount, pas payment.amount en XAF), XOF, content_ids');
s.verifier(u.em[0] === s.sha('awa.test@gmail.com') && u.external_id[0] === u.em[0], 'e-mail normalisé puis haché (em, external_id)');
s.verifier(u.ph[0] === s.sha('2290197000000'), 'téléphone de la fiche (phone.number + dial_code) haché');
s.verifier(u.fn[0] === s.sha('awa') && u.ln[0] === s.sha('kossou') && u.country[0] === s.sha('bj'), 'prénom, nom, pays hachés');
s.verifier(u.client_ip_address === '160.155.244.158' && u.client_user_agent === 'Mozilla/5.0 (Linux; Android 14) Chariow', 'IP et navigateur du paiement (fiche Chariow)');
s.verifier(u.fbp === 'fb.1.1760000000000.1234567890' && u.fbc === 'fb.1.1760000000000.IwAR0abc_DEF-123', 'fbp et fbc du signal');
s.verifier(!('test_event_code' in e.envoisMeta[0].corps), 'pas de test_event_code');
s.verifier(e.envoisMeta[0].url.startsWith('https://graph.facebook.com/v25.0/5010730402487338/events'), 'API Meta v25.0, Pixel Livensya');
s.verifier(statut(e).startsWith('Envoyé') && s.ventes(e)[0][6] === 'fbp fbc' && s.ventes(e)[0][5] === '160.155.x.x', 'onglet Ventes : ' + statut(e) + ', IP masquée');
passage(e, 4);
s.verifier(s.purchases(e).length === 1, 'déclencheur des 5 min : pas de doublon');

console.log('\n2. Webhook renvoyé, signal répété, rechargement');
e = s.charger(); e.fiches.SALEB2 = s.fiche('SALEB2');
s.post(e, s.webhook('SALEB2')); s.post(e, s.webhook('SALEB2'));
s.post(e, s.signal('SALEB2')); s.post(e, s.signal('SALEB2'));
s.post(e, s.webhook('SALEB2'));
passage(e, 6);
s.verifier(s.purchases(e).length === 1 && s.ventes(e).length === 1 && e.lecturesChariow.length === 1, '1 Purchase, 1 ligne Ventes, 1 lecture Chariow');
s.verifier(s.debug(e).filter(l => l.startsWith('Doublon ignoré')).length === 2, '2 renvois notés « Doublon ignoré »');

console.log('\n3. Signal AVANT le webhook');
e = s.charger(); e.fiches.SALEC3 = s.fiche('SALEC3');
s.post(e, s.signal('SALEC3'));
s.verifier(s.purchases(e).length === 0, 'signal seul : rien envoyé');
s.post(e, s.webhook('SALEC3'));
p = s.purchases(e);
s.verifier(p.length === 1 && p[0].user_data.fbp && p[0].user_data.fbc, 'webhook : Purchase tout de suite, avec fbp/fbc');

console.log('\n4. Signal absent : envoi sans fbp/fbc après l\'attente');
e = s.charger(); e.fiches.SALED4 = s.fiche('SALED4');
s.post(e, s.webhook('SALED4'));
passage(e, 1);
s.verifier(s.purchases(e).length === 0, 'à 5 min : en attente');
passage(e, 1, 6 * MIN);
p = s.purchases(e);
s.verifier(p.length === 1 && !p[0].user_data.fbp && !p[0].user_data.fbc && p[0].user_data.client_ip_address, 'à 11 min : envoyé sans fbp/fbc, avec IP');
s.verifier(p[0].event_source_url === 'https://livensya.emkbluediamond.online/' && s.ventes(e)[0][6] === 'non', 'adresse du site par défaut, signal « non »');
s.post(e, s.signal('SALED4'));
s.verifier(s.purchases(e).length === 1, 'signal tardif ignoré');

console.log('\n5. Autre produit, autre boutique, produit absent');
e = s.charger();
s.post(e, s.webhook('SALEE5', { product: { id: 'prd_qh7md6nj' } }));
s.post(e, s.webhook('SALEE6', { store: { id: 'store_xfu1kqhyz8ds', url: 'https://emkbluediamond.mychariow.shop' } }));
s.post(e, s.webhook('SALEE9', { product: undefined }));
s.verifier(s.purchases(e).length === 0 && e.lecturesChariow.length === 0 && s.ventes(e).length === 0, 'webhooks ignorés sans lecture Chariow');
e.fiches.SALEE7 = s.fiche('SALEE7', { product: { id: 'prd_autre' } });
s.post(e, s.webhook('SALEE7'));
s.verifier(s.purchases(e).length === 0 && s.debug(e).some(l => l.includes('autre produit')), 'fiche d\'un autre produit : refusée');
e.fiches.SALEE8 = s.fiche('SALEE8', { store: { id: 'store_xfu1kqhyz8ds' } });
s.post(e, s.webhook('SALEE8'));
s.verifier(s.purchases(e).length === 0 && s.debug(e).some(l => l.includes('autre boutique')), 'fiche d\'une autre boutique (store.id) : refusée');
e.fiches.SALEU = s.fiche('SALEU', { store: { url: 'https://autre.mychariow.store' } });
s.post(e, s.webhook('SALEU', { store: { url: 'https://autre.mychariow.store' } })); s.post(e, s.signal('SALEU'));
s.verifier(s.purchases(e).length === 1 && s.debug(e).some(l => l.startsWith('Attention | adresse de boutique')), 'store.id absent, adresse différente : non bloquant, juste signalé');
e = s.charger(); e.fiches.SALEP = s.fiche('SALEP', { product: undefined });
s.post(e, s.webhook('SALEP'));
s.verifier(s.purchases(e).length === 0 && s.debug(e).some(l => l.includes('produit absent')), 'fiche sans produit : rien envoyé, nouvel essai prévu');
passage(e, 12);
s.verifier(statut(e).startsWith('Échec : produit absent'), 'après 1 h : échec visible dans Ventes (' + statut(e).slice(0, 40) + '…)');
s.post(e, { event: 'abandoned.sale', sale: { id: 'SALEE8' }, product: { id: 'prd_4bisyd7x' } });
s.verifier(s.purchases(e).length === 0, 'panier abandonné : ignoré');

console.log('\n6. Faux webhook, ventes non payées');
e = s.charger();
s.post(e, s.webhook('SALEFAUX')); passage(e, 6); s.post(e, s.webhook('SALEFAUX'));
s.verifier(s.purchases(e).length === 0 && s.ventes(e).length === 0, 'vente inexistante : aucun Purchase, aucune ligne');
s.verifier(s.debug(e).some(l => l.startsWith('Refusé') && l.includes('inconnue')) && ![...e.props.keys()].some(k => k.startsWith('vente_')), '« Refusé : vente inconnue », rien gardé en mémoire');
for (const [st, ps] of [['failed', 'failed'], ['completed', 'cancelled'], ['refunded', 'success'], ['abandoned', ''], ['expired', '']]) {
  e = s.charger(); e.fiches.SALEF = s.fiche('SALEF', { status: st, payment: { status: ps } });
  s.post(e, s.webhook('SALEF')); passage(e, 3);
  s.verifier(s.purchases(e).length === 0 && s.ventes(e).length === 0, 'statut « ' + st + ' », paiement « ' + ps + ' » : refusé');
}
for (const [st, ps] of [['completed', 'success'], ['settled', 'success'], ['paid', ''], ['success', ''], ['autre_chose', 'success']]) {
  e = s.charger(); e.fiches.SALEOK = s.fiche('SALEOK', { status: st, payment: { status: ps } });
  s.post(e, s.webhook('SALEOK')); s.post(e, s.signal('SALEOK'));
  s.verifier(s.purchases(e).length === 1, 'statut « ' + st + ' », paiement « ' + ps + ' » : accepté');
}
e = s.charger(); e.fiches.SALEX = s.fiche('SALEX', { status: 'en_revue', payment: { status: 'pending' } });
s.post(e, s.webhook('SALEX')); s.post(e, s.signal('SALEX'));
s.verifier(s.purchases(e).length === 0 && s.debug(e).some(l => l.includes('inconnu')), 'statut inconnu : pas envoyé, nouvel essai');
passage(e, 12);
s.verifier(s.purchases(e).length === 0 && statut(e).startsWith('Échec : statut'), 'après 1 h : « Échec » visible dans Ventes');
e.fiches.SALEX = s.fiche('SALEX'); s.post(e, s.webhook('SALEX')); s.post(e, s.signal('SALEX'));
s.verifier(s.purchases(e).length === 1, 'rejeu de la livraison Chariow après l\'échec : envoyé une fois');
s.post(e, s.webhook('SALEX'));
s.verifier(s.purchases(e).length === 1, 'nouveau rejeu : doublon ignoré');

console.log('\n7. IP, fbp, fbc, URL invalides écartés');
for (const ip of ['192.168.1.10', '10.0.0.1', '1.2.3', 'abc', '::1', 'fe80::1', ' 160.155.244.158 x']) {
  e = s.charger(); e.fiches.SALEG = s.fiche('SALEG', { context: { ip_address: ip, user_agent: 'UA', country: { code: 'BJ' } } });
  s.post(e, s.webhook('SALEG')); s.post(e, s.signal('SALEG'));
  p = s.purchases(e);
  s.verifier(p.length === 1 && !('client_ip_address' in p[0].user_data), 'IP « ' + ip + ' » non envoyée, achat envoyé');
}
s.verifier(e.api.ipValide_('2c0f:f0f8:1::5') === '2c0f:f0f8:1::5' && e.api.ipValide_('::ffff:192.168.0.1') === '', 'IPv6 publique gardée, IPv4 privée déguisée écartée');
e = s.charger(); e.fiches.SALEI = s.fiche('SALEI');
s.post(e, s.webhook('SALEI'));
s.post(e, { purchaseId: 'SALEI', _fbp: 'pas un fbp', _fbc: 'fb.1.123.<script>', _userAgent: 'UA', _eventSourceUrl: 'https://pirate.example/' });
p = s.purchases(e);
s.verifier(p.length === 1 && !p[0].user_data.fbp && !p[0].user_data.fbc && p[0].event_source_url === 'https://livensya.emkbluediamond.online/', 'fbp, fbc et adresse invalides écartés');
e = s.charger();
s.post(e, { purchaseId: '../../x', _fbp: 'fb.1.1760000000000.1' });
s.verifier(![...e.props.keys()].some(k => k.startsWith('signal_')), 'identifiant de signal invalide : rien gardé');

console.log('\n8. Code de test : jamais sur les vraies ventes');
e = s.charger({ codeTest: 'TEST12345' }); e.fiches.SALEH8 = s.fiche('SALEH8');
s.post(e, s.webhook('SALEH8')); s.post(e, s.signal('SALEH8'));
s.verifier(e.envoisMeta.length === 1 && !('test_event_code' in e.envoisMeta[0].corps), 'vraie vente : pas de test_event_code même si le code est rempli');
s.verifier(!statut(e).includes('test'), 'onglet Ventes : ' + statut(e));

console.log('\n9. testerAchatFictif');
e = s.charger();
r = e.api.testerAchatFictif();
s.verifier(e.envoisMeta.length === 0 && r.startsWith('Refusé'), 'sans code de test : refusé, rien envoyé');
e = s.charger({ codeTest: 'TEST999' });
r = e.api.testerAchatFictif();
p = e.envoisMeta[0] && e.envoisMeta[0].corps;
s.verifier(e.envoisMeta.length === 1 && p.test_event_code === 'TEST999', 'avec code : 1 envoi, avec test_event_code');
s.verifier(p && p.data[0].event_id.startsWith('TEST-') && p.data[0].custom_data.content_name.startsWith('TEST') && s.ventes(e).length === 0, 'marqué TEST, rien dans Ventes');

console.log('\n10. Pannes Chariow et Meta');
e = s.charger(); e.fiches.SALEJ1 = { code: 500 };
s.post(e, s.webhook('SALEJ1'));
s.verifier(s.purchases(e).length === 0 && s.debug(e).some(l => l.startsWith('Nouvel essai')), 'Chariow 500 : nouvel essai prévu');
e.fiches.SALEJ1 = s.fiche('SALEJ1'); passage(e, 1);
s.verifier(s.ventes(e).length === 1, 'Chariow revenu : vérifiée au passage suivant');
e.reponsesMeta.push({ code: 500, corps: { error: { message: 'Indisponible' } } });
passage(e, 1, 6 * MIN);
s.verifier(statut(e).startsWith('Erreur Meta, nouvel essai'), 'Meta 500 : ' + statut(e).slice(0, 40));
passage(e, 3);
s.verifier(e.envoisMeta.length === 2 && statut(e).startsWith('Envoyé'), '2e essai réussi, puis plus rien');
e = s.charger(); e.fiches.SALEJ5 = s.fiche('SALEJ5');
e.reponsesMeta.push('exception', { code: 200, corps: { events_received: 0, messages: ['?'] } });
s.post(e, s.webhook('SALEJ5')); s.post(e, s.signal('SALEJ5'));
s.verifier(statut(e).includes('Meta injoignable'), 'exception réseau Meta : nouvel essai');
passage(e, 1);
s.verifier(statut(e).startsWith('Erreur Meta') && statut(e).includes('code 200'), 'events_received 0 : pas compté comme envoyé, nouvel essai');
passage(e, 3);
s.verifier(e.envoisMeta.length === 3 && statut(e).startsWith('Envoyé'), '3e essai réussi, puis plus rien');
e = s.charger(); e.fiches.SALEJ6 = s.fiche('SALEJ6');
for (let i = 0; i < 20; i++) e.reponsesMeta.push({ code: 503, corps: {} });
s.post(e, s.webhook('SALEJ6')); s.post(e, s.signal('SALEJ6'));
passage(e, 15);
s.verifier(e.envoisMeta.length === 12 && statut(e).startsWith('Échec Meta'), 'Meta en panne : 12 essais au plus, puis « Échec Meta »');
e.reponsesMeta.length = 0;
s.post(e, s.webhook('SALEJ6')); s.post(e, s.signal('SALEJ6'));
s.verifier(e.envoisMeta.length === 13 && statut(e).startsWith('Envoyé'), 'rejeu Chariow après l\'abandon : envoyé');
e = s.charger(); e.fiches.SALEJ2 = s.fiche('SALEJ2');
e.reponsesMeta.push({ code: 400, corps: { error: { message: 'Invalid parameter', code: 100 } } });
s.post(e, s.webhook('SALEJ2')); s.post(e, s.signal('SALEJ2')); passage(e, 6);
s.verifier(e.envoisMeta.length === 1 && statut(e).startsWith('Échec Meta'), 'Meta 400 : pas de relance inutile');
e = s.charger({ jeton: '' }); e.fiches.SALEJ3 = s.fiche('SALEJ3');
s.post(e, s.webhook('SALEJ3')); s.post(e, s.signal('SALEJ3'));
s.verifier(e.envoisMeta.length === 0 && statut(e).includes('META_ACCESS_TOKEN absent'), 'jeton oublié : la vente attend');
e.props.set('META_ACCESS_TOKEN', s.JETON); passage(e, 1);
s.verifier(s.purchases(e).length === 1 && s.purchases(e)[0].user_data.fbp, 'jeton ajouté : envoyée, avec fbp');
for (const rm of [{ code: 400, corps: { error: { message: 'Invalid OAuth access token', code: 190 } } }, { code: 400, corps: { error: { code: 102 } } }, { code: 401, corps: {} }, { code: 403, corps: {} }]) {
  e = s.charger(); e.fiches.SALEJ7 = s.fiche('SALEJ7');
  for (let i = 0; i < 30; i++) e.reponsesMeta.push(rm);
  s.post(e, s.webhook('SALEJ7')); s.post(e, s.signal('SALEJ7')); passage(e, 20);
  s.verifier(statut(e).includes('jeton Meta refusé') && !statut(e).startsWith('Échec'), 'jeton refusé (' + rm.code + '/' + ((rm.corps.error || {}).code || '-') + ') : attente sans abandon après 21 essais');
  e.reponsesMeta.length = 0; passage(e, 1);
  s.verifier(statut(e).startsWith('Envoyé'), 'jeton remplacé : envoyée');
}
e = s.charger(); e.fiches.SALEJ4 = s.fiche('SALEJ4', { status: 'awaiting_payment', payment: { status: 'pending' } });
s.post(e, s.webhook('SALEJ4'));
e.fiches.SALEJ4 = s.fiche('SALEJ4'); passage(e, 3);
s.verifier(s.purchases(e).length === 1, 'paiement pas encore confirmé : revérifié puis envoyé une fois');

console.log('\n11. Verrou occupé, écriture impossible');
e = s.charger(); e.fiches.SALEV = s.fiche('SALEV');
e.pannes.verrouLibre = false;
s.post(e, s.webhook('SALEV'));
s.verifier(e.props.has('brut_SALEV') && e.lecturesChariow.length === 0, 'verrou occupé : vente mise en file (brut_)');
s.post(e, s.signal('SALEV'));
s.verifier(s.debug(e).some(l => l.startsWith('Signal perdu')), 'signal pendant le verrou occupé : noté « Signal perdu »');
passage(e, 1);
s.verifier(e.props.has('brut_SALEV'), 'toujours occupé : la vente reste en file');
e.pannes.verrouLibre = true; passage(e, 1);
s.verifier(!e.props.has('brut_SALEV') && e.lecturesChariow.length === 1, 'verrou libre : reprise, fiche lue une seule fois dans le passage');
passage(e, 3);
s.verifier(s.purchases(e).length === 1, 'puis envoyée une fois (sans fbp/fbc)');
e = s.charger();
for (let i = 0; i < 52; i++) { e.fiches['SALEQ' + i] = { code: 500 }; s.post(e, s.webhook('SALEQ' + i)); }
s.verifier(e.props.has('brut_SALEQ50') && e.props.has('brut_SALEQ51') && !e.props.has('vente_SALEQ50'), 'plafond de 50 ventes en vérification : les suivantes mises en file, pas ignorées');
for (let i = 0; i < 52; i++) e.fiches['SALEQ' + i] = s.fiche('SALEQ' + i);
passage(e, 4);
s.verifier(s.purchases(e).length === 52, 'toutes envoyées ensuite (' + s.purchases(e).length + '/52)');
s.verifier(new Set(e.lecturesChariow.slice(52).map(x => x.id)).size === e.lecturesChariow.slice(52).length, 'pas deux lectures Chariow de la même vente dans un passage');
e = s.charger(); e.fiches.SALEV2 = { code: 500 };
e.pannes.verrouLibre = false; s.post(e, s.webhook('SALEV2')); e.pannes.verrouLibre = true;
passage(e, 1);
s.verifier(e.lecturesChariow.length === 1, 'vente reprise de la file et Chariow toujours en panne : 1 seule lecture dans le passage (' + e.lecturesChariow.length + ')');
e = s.charger(); e.fiches.SALEW = s.fiche('SALEW');
e.pannes.bloquerEcriture = (k, v) => k === 'vente_SALEW' && v.includes('"envoye"');
s.post(e, s.webhook('SALEW')); s.post(e, s.signal('SALEW'));
s.verifier(e.envoisMeta.length === 1 && s.debug(e).some(l => l.startsWith('ERREUR') && l.includes('impossible de noter')), '200 de Meta puis écriture impossible : journalisé');
passage(e, 10);
s.verifier(e.envoisMeta.length === 1, 'aucun renvoi en boucle (l\'onglet Ventes « Envoyé » bloque)');
e = s.charger(); e.fiches.SALEW2 = s.fiche('SALEW2');
e.pannes.bloquerEcriture = (k, v) => k === 'vente_SALEW2' && v.includes('"envoye"') && v.includes('"id"');
s.post(e, s.webhook('SALEW2')); s.post(e, s.signal('SALEW2'));
s.verifier(e.props.get('vente_SALEW2') === '{"etape":"envoye"}' && s.debug(e).some(l => l.includes('version minimale')), 'écriture complète refusée : écriture minimale faite');
passage(e, 3); s.post(e, s.webhook('SALEW2'));
s.verifier(e.envoisMeta.length === 1, 'pas de renvoi');
e = s.charger(); e.fiches.SALEZ1 = s.fiche('SALEZ1'); e.fiches.SALEZ2 = s.fiche('SALEZ2');
s.post(e, s.webhook('SALEZ1')); s.post(e, s.webhook('SALEZ2'));
e.props.set('vente_SALEZ1', '{pas du json');
passage(e, 3);
s.verifier(s.purchases(e).some(x => x.event_id === 'SALEZ2') && s.debug(e).some(l => l.startsWith('ERREUR | vente_SALEZ1')), 'état abîmé d\'une vente : erreur notée, les autres continuent');

console.log('\n12. Montant, devise, heure');
e = s.charger(); e.fiches.SALEM0 = s.fiche('SALEM0', { amount: { value: 0, currency: 'XOF' } });
s.post(e, s.webhook('SALEM0')); s.post(e, s.signal('SALEM0'));
s.verifier(s.purchases(e)[0].custom_data.value === 0, 'montant 0 (code promo 100 %) : value 0, pas 3999');
e = s.charger(); e.fiches.SALEM1 = s.fiche('SALEM1', { amount: { value: 2500, currency: { code: 'XOF' } } });
s.post(e, s.webhook('SALEM1')); s.post(e, s.signal('SALEM1'));
s.verifier(s.purchases(e)[0].custom_data.value === 2500 && s.purchases(e)[0].custom_data.currency === 'XOF', 'devise sous forme d\'objet {code} : lue');
e = s.charger(); e.fiches.SALEM2 = s.fiche('SALEM2', { amount: { value: 2500, currency: { nom: 'franc' } } });
s.post(e, s.webhook('SALEM2')); s.post(e, s.signal('SALEM2'));
s.verifier(s.purchases(e)[0].custom_data.currency === 'XOF' && s.debug(e).some(l => l.includes('devise illisible')), 'devise illisible : XOF et note dans _Debug');
e = s.charger(); e.fiches.SALEM3 = s.fiche('SALEM3', { amount: undefined });
s.post(e, s.webhook('SALEM3')); s.post(e, s.signal('SALEM3'));
s.verifier(s.purchases(e)[0].custom_data.value === 3999, 'montant absent : 3999');
e = s.charger(); e.fiches.SALET = s.fiche('SALET', { completed_at: '2026-10-09T13:00:00.000000Z' });
s.post(e, s.webhook('SALET')); s.post(e, s.signal('SALET'));
s.verifier(s.purchases(e)[0].event_time === Math.floor(e.maintenant() / 1000), 'heure de vente dans le futur : event_time = maintenant');
e = s.charger(); e.fiches.SALEL = s.fiche('SALEL', { completed_at: '2026-10-01T09:00:00+00:00' });
s.post(e, s.webhook('SALEL')); s.post(e, s.signal('SALEL'));
s.verifier(e.envoisMeta.length === 0 && s.debug(e).some(l => l.includes('plus de 7 jours')), 'vente de plus de 7 jours : refusée');
e = s.charger(); e.fiches.SALEUA = s.fiche('SALEUA', { context: { ip_address: '160.155.244.158', country: { code: 'BJ' } } });
s.post(e, s.webhook('SALEUA')); s.post(e, { purchaseId: 'SALEUA', _fbp: 'fb.1.1760000000000.1' });
s.verifier(s.purchases(e).length === 1 && !s.purchases(e)[0].user_data.client_user_agent && s.debug(e).some(l => l.includes('client_user_agent')), 'navigateur inconnu : envoyé quand même, noté dans _Debug');

console.log('\n13. Ventes d\'affiliés');
e = s.charger(); e.fiches.SALEAF = s.fiche('SALEAF', { channel: { value: 'affiliate' } });
s.post(e, s.webhook('SALEAF')); s.post(e, s.signal('SALEAF')); passage(e, 3);
s.verifier(e.envoisMeta.length === 0 && statut(e) === 'Vente affilié, non envoyée', 'fiche « affilié » : pas envoyée, ligne visible');
s.post(e, s.webhook('SALEAF'));
s.verifier(s.ventes(e).length === 1, 'renvoi : doublon ignoré');
e = s.charger(); e.fiches.SALEAF2 = s.fiche('SALEAF2', { store_affiliate: { id: 'saff_1', code: 'AMI' } });
s.post(e, s.webhook('SALEAF2'));
s.verifier(e.envoisMeta.length === 0 && statut(e).startsWith('Vente affilié'), 'fiche avec store_affiliate : pas envoyée');
e = s.charger(); e.fiches.SALEAF3 = s.fiche('SALEAF3');
s.post(e, s.webhook('SALEAF3', { affiliate: { id: 'aff_pirate', code: 'X' } }));
s.verifier(e.envoisMeta.length === 0 && statut(e) === 'En attente du signal de la page', 'webhook forgé « affilié » mais fiche « widget » : la fiche fait foi, rien de bloqué');
s.post(e, s.signal('SALEAF3'));
s.verifier(s.purchases(e).length === 1, 'la vraie vente part normalement');
e = s.charger(); const f4 = s.fiche('SALEAF4'); delete f4.channel; e.fiches.SALEAF4 = f4;
s.post(e, s.webhook('SALEAF4', { affiliate: { id: 'aff_x' } }));
s.verifier(statut(e).includes('d\'après le webhook') && !e.props.has('vente_SALEAF4'), 'fiche muette, webhook « affilié » : non envoyée, AUCUN état gardé');
s.post(e, s.webhook('SALEAF4')); s.post(e, s.signal('SALEAF4'));
s.verifier(s.purchases(e).length === 1, 'le vrai webhook (sans affilié) passe ensuite : envoyé');

console.log('\n14. Purge, configuration, secrets');
e = s.charger(); e.fiches.SALEPU = s.fiche('SALEPU', { completed_at: new Date(e.maintenant()).toISOString() });
s.post(e, s.webhook('SALEPU')); s.post(e, s.signal('SALEPU'));
e.props.set('vente_ECHECVIEUX', JSON.stringify({ id: 'ECHECVIEUX', etape: 'echec', t: e.maintenant() }));
passage(e, 1, 9 * JOUR);
s.verifier(e.props.has('vente_SALEPU') && e.props.has('vente_ECHECVIEUX'), 'à 9 jours : mémoire gardée');
passage(e, 1, 2 * JOUR);
s.verifier(!e.props.has('vente_SALEPU') && !e.props.has('vente_ECHECVIEUX'), 'à 11 jours : états « envoye » et « echec » purgés');
s.post(e, s.webhook('SALEPU'));
s.verifier(e.envoisMeta.length === 1, 'rejeu après la purge : vente de plus de 7 jours refusée, pas de renvoi');
e = s.charger({ jeton: '', cleChariow: '' });
r = e.api.verifierConfiguration();
s.verifier(r.includes('MANQUE : META_ACCESS_TOKEN') && r.includes('MANQUE : CHARIOW_API_KEY') && r.includes('testerAchatFictif refusera'), 'dit ce qui manque');
e.api.verifierConfiguration();
s.verifier(e.declencheurs.length === 1 && e.declencheurs[0] === 'envoyerEnAttente', 'un seul déclencheur, même relancée');
s.post(e, s.webhook('SALEN'));
passage(e, 20);
s.verifier(s.debug(e).filter(l => l.startsWith('Nouvel essai')).length === 1, 'clé Chariow absente : la vente attend, une seule ligne _Debug');
e.props.set('CHARIOW_API_KEY', s.CLE_CHARIOW); e.props.set('META_ACCESS_TOKEN', s.JETON);
e.fiches.SALEN = s.fiche('SALEN', { completed_at: new Date(e.maintenant()).toISOString() });
passage(e, 3);
s.verifier(s.purchases(e).length === 1, 'clés ajoutées : vérifiée puis envoyée une fois');
e = s.charger({ codeTest: 'TEST1' });
r = e.api.verifierConfiguration();
s.verifier(r.includes('OK : META_ACCESS_TOKEN') && r.includes('sert seulement à testerAchatFictif'), 'tout rempli : OK');
e.fiches.SALEK = s.fiche('SALEK');
e.reponsesMeta.push({ code: 400, corps: { error: { message: 'Bad token ' + s.JETON } } });
s.post(e, s.webhook('SALEK')); s.post(e, s.signal('SALEK'));
const toutTexte = JSON.stringify(e.feuilles) + r + e.logs.join('\n');
s.verifier(!toutTexte.includes(s.JETON) && !toutTexte.includes(s.CLE_CHARIOW) && !toutTexte.includes('160.155.244.158'), 'aucun secret ni IP complète dans les onglets et journaux');
s.verifier(e.lecturesChariow[0].auth === 'Bearer ' + s.CLE_CHARIOW, 'la clé Chariow ne sert qu\'à l\'appel Chariow');
s.verifier(JSON.parse(e.api.doGet().texte).status === 'ok', 'doGet renvoie {status:"ok"}');

console.log('\n15. Divers');
e = s.charger();
for (let i = 0; i < 3; i++) s.post(e, s.signal('SALEINCONNUE' + i));
passage(e, 1, 25 * 3600 * 1000);
s.verifier(![...e.props.keys()].some(k => k.startsWith('signal_')) && s.debug(e).filter(l => l.startsWith('Signal sans vente')).length === 3, 'signaux sans vente effacés après 24 h et signalés');
s.verifier(e.api.telephone_('97000000', '') === '' && e.api.telephone_('0612345678', '+33') === '33612345678' && e.api.telephone_('0197000000', '+229') === '2290197000000' && e.api.telephone_('237693182541', '+237') === '237693182541', 'téléphones : complétés, gardés ou écartés');
e = s.charger(); const fm = s.fiche('SALEMC'); delete fm.customer.phone; e.fiches.SALEMC = fm;
s.post(e, s.webhook('SALEMC', { customer: { email: 'autre@gmail.com', phone: '+22990000000', country: 'BJ' } }));
s.post(e, s.signal('SALEMC'));
s.verifier(s.purchases(e).length === 1 && !s.purchases(e)[0].user_data.ph, 'fiche sans téléphone, webhook d\'un autre e-mail : téléphone du webhook non utilisé');
e = s.charger(); const fm2 = s.fiche('SALEMD'); delete fm2.customer.phone; e.fiches.SALEMD = fm2;
s.post(e, s.webhook('SALEMD')); s.post(e, s.signal('SALEMD'));
s.verifier(s.purchases(e)[0].user_data.ph[0] === s.sha('2290197000000'), 'fiche sans téléphone, webhook du même client : son téléphone sert de secours');
e.api.doPost({ postData: { contents: 'pas du json' } });
s.verifier(s.debug(e).some(l => l.startsWith('Ignoré | message illisible')), 'message illisible : ignoré sans erreur');

const b = s.bilan();
console.log('\n' + (b.echecs ? 'ÉCHECS : ' + b.echecs + ' sur ' + b.total : 'TOUT EST OK : ' + b.total + ' vérifications'));
process.exit(b.echecs ? 1 : 0);
