import type { Agent, Project, MemoryEntry, Mission, AvatarConfig } from './types';

// Morphology for the hand-drawn SVG avatars (rendered by AgentAvatarSVG).
export const AVATAR_CONFIG: Record<string, AvatarConfig> = {
  raphael: { skin: '#D4A76A', hair: '#2C1810', outfit: '#4C1D95', hasCrown: true, hasTie: true },
  sofia:   { skin: '#F0C49A', hair: '#3B1A08', outfit: '#1E3A8A', female: true },
  gabriel: { skin: '#7D4E2D', hair: '#1A0A00', outfit: '#0F766E', hasGlasses: true },
  elena:   { skin: '#F5D0B5', hair: '#8B2500', outfit: '#9D174D', female: true },
  nathan:  { skin: '#C49A6C', hair: '#1F1008', outfit: '#9A3412', hasBeard: true },
  maya:    { skin: '#553322', hair: '#1A0900', outfit: '#991B1B', female: true, braids: true },
  lucas:   { skin: '#E8C49A', hair: '#C4943E', outfit: '#166534' },
  emma:    { skin: '#C8956C', hair: '#0D0D0D', outfit: '#1D4ED8', female: true, hasGlasses: true },
  adam:    { skin: '#3D2B1F', hair: '#1A0900', outfit: '#92400E', hasTie: true },
  noah:    { skin: '#B87D5B', hair: '#2C1810', outfit: '#881337', hasBeard: true, hasBeret: true },
  lea:     { skin: '#F0C49A', hair: '#2C1810', outfit: '#312E81', female: true, hasBob: true },
};

export const AGENTS: Agent[] = [
  {
    id: 'raphael',
    name: 'Raphaël',
    role: 'Orchestrateur Central',
    title: 'Directeur Intelligence & Coordination',
    color: '#7C3AED',
    gradient: ['#8B5CF6', '#4C1D95'],
    emoji: '🧠',
    skills: ['Coordination', 'Analyse stratégique', 'Planification', 'Synthèse', 'Leadership'],
    status: 'active',
    tasksCompleted: 1247,
    successRate: 97.8,
    description: 'Intelligence centrale d\'Angeleck. Analyse, planifie, coordonne et synthétise chaque mission.',
    personality: ['Calme', 'Analytique', 'Stratégique', 'Orienté résultat'],
    tools: ['Tous les agents', 'Genesis Engine', 'Akasha Memory', 'Guardian'],
    limits: 'Valide les décisions critiques avec l\'humain',
  },
  {
    id: 'sofia',
    name: 'Sofia',
    role: 'Directrice Business',
    title: 'Stratégie & Croissance',
    color: '#1E40AF',
    gradient: ['#60A5FA', '#1E3A8A'],
    emoji: '👩‍💼',
    skills: ['Business model', 'Opportunités marché', 'Analyse concurrence', 'Croissance'],
    status: 'idle',
    tasksCompleted: 342,
    successRate: 95.2,
    description: 'Expert en stratégie entrepreneuriale, modèles économiques et développement commercial.',
    personality: ['Ambitieuse', 'Analytique', 'Visionnaire'],
    tools: ['Analyse marché', 'Modélisation financière', 'Benchmarking'],
    limits: 'Recommande, ne décide pas seule les pivots stratégiques majeurs',
  },
  {
    id: 'maya',
    name: 'Maya',
    role: 'Directrice Marketing',
    title: 'Acquisition & Croissance',
    color: '#DC2626',
    gradient: ['#F87171', '#991B1B'],
    emoji: '📢',
    skills: ['Meta Ads', 'Google Ads', 'TikTok', 'SEO', 'Tunnels de vente'],
    status: 'idle',
    tasksCompleted: 589,
    successRate: 93.4,
    description: 'Spécialiste en acquisition client, campagnes publicitaires et stratégies de croissance digitale.',
    personality: ['Dynamique', 'Data-driven', 'Créative'],
    tools: ['Meta Ads API', 'Google Analytics', 'Semrush', 'A/B testing'],
    limits: 'Ne dépense jamais de budget sans validation',
  },
  {
    id: 'nathan',
    name: 'Nathan',
    role: 'Expert Copywriting',
    title: 'Rédaction Persuasive',
    color: '#C2410C',
    gradient: ['#FB923C', '#9A3412'],
    emoji: '✍️',
    skills: ['Pages de vente', 'Emails', 'Scripts vidéo', 'Publicités', 'Persuasion'],
    status: 'idle',
    tasksCompleted: 891,
    successRate: 96.1,
    description: 'Maître de la persuasion écrite. Transforme les idées en messages qui convertissent.',
    personality: ['Précis', 'Empathique', 'Créatif'],
    tools: ['Rédaction longform', 'Email sequences', 'Script writing'],
    limits: 'Vérifie l\'exactitude des informations avec les autres agents',
  },
  {
    id: 'elena',
    name: 'Elena',
    role: 'Directrice Créative',
    title: 'Identité Visuelle & Branding',
    color: '#BE185D',
    gradient: ['#F472B6', '#9D174D'],
    emoji: '👩‍🎨',
    skills: ['Branding', 'Direction artistique', 'Visuels publicitaires', 'Storytelling'],
    status: 'idle',
    tasksCompleted: 476,
    successRate: 94.7,
    description: 'Créatrice d\'univers visuels premium. Traduit les émotions en expériences esthétiques.',
    personality: ['Intuitive', 'Perfectionniste', 'Artistique'],
    tools: ['DALL-E', 'Midjourney', 'Figma', 'Adobe Creative'],
    limits: 'Valide les créations finales avec le client',
  },
  {
    id: 'gabriel',
    name: 'Gabriel',
    role: 'Architecte Technologie',
    title: 'Infrastructure & Automatisation',
    color: '#0D9488',
    gradient: ['#2DD4BF', '#0F766E'],
    emoji: '👨‍💻',
    skills: ['Architecture système', 'API', 'Automatisation', 'IA', 'DevOps'],
    status: 'idle',
    tasksCompleted: 267,
    successRate: 98.5,
    description: 'Architecte des solutions techniques. Construit les infrastructures qui font fonctionner les idées.',
    personality: ['Rigoureux', 'Innovant', 'Systématique'],
    tools: ['Code generation', 'API design', 'n8n', 'Docker', 'AWS'],
    limits: 'Valide les déploiements en production avec l\'humain',
  },
  {
    id: 'lucas',
    name: 'Lucas',
    role: 'Directeur E-commerce',
    title: 'Boutiques Digitales & Conversion',
    color: '#15803D',
    gradient: ['#4ADE80', '#166534'],
    emoji: '🛒',
    skills: ['Shopify', 'Chariow', 'Conversion', 'UX', 'Marketplaces'],
    status: 'idle',
    tasksCompleted: 318,
    successRate: 91.8,
    description: 'Expert en commerce en ligne. Crée des boutiques qui convertissent et des expériences d\'achat mémorables.',
    personality: ['Orienté résultats', 'Empathique', 'Pragmatique'],
    tools: ['Shopify', 'WooCommerce', 'Stripe', 'Analytics'],
    limits: 'Limite les modifications de données clients sans permission',
  },
  {
    id: 'emma',
    name: 'Emma',
    role: 'Analyste Data',
    title: 'Intelligence Marché & Données',
    color: '#1D4ED8',
    gradient: ['#93C5FD', '#1D4ED8'],
    emoji: '📊',
    skills: ['Analyse marché', 'Statistiques', 'Tendances', 'KPIs', 'Prévisions'],
    status: 'idle',
    tasksCompleted: 531,
    successRate: 95.9,
    description: 'Transforme les données brutes en insights actionnables. La boussole data de l\'équipe.',
    personality: ['Précise', 'Curieuse', 'Objective'],
    tools: ['Python analytics', 'Tableau', 'BigQuery', 'Airtable'],
    limits: 'Présente les données sans les interpréter de façon biaisée',
  },
  {
    id: 'adam',
    name: 'Adam',
    role: 'Directeur Finance',
    title: 'Rentabilité & Investissement',
    color: '#B45309',
    gradient: ['#FCD34D', '#92400E'],
    emoji: '💰',
    skills: ['Marges', 'ROI', 'Prévisions', 'Cash flow', 'Investissement'],
    status: 'idle',
    tasksCompleted: 224,
    successRate: 97.3,
    description: 'Gardien de la rentabilité. S\'assure que chaque décision est financièrement solide.',
    personality: ['Prudent', 'Analytique', 'Rigoureux'],
    tools: ['Modélisation financière', 'Excel/Sheets avancé', 'Comptabilité'],
    limits: 'Toujours transparent sur les risques financiers',
  },
  {
    id: 'noah',
    name: 'Noah',
    role: 'Producteur Média',
    title: 'Contenu Audiovisuel Premium',
    color: '#9F1239',
    gradient: ['#FB7185', '#881337'],
    emoji: '🎬',
    skills: ['Vidéos publicitaires', 'Montage', 'Scripts', 'Réseaux sociaux'],
    status: 'idle',
    tasksCompleted: 408,
    successRate: 92.6,
    description: 'Créateur de contenus vidéo premium. Donne vie aux histoires de marque avec impact émotionnel.',
    personality: ['Créatif', 'Perfectionniste', 'Storyteller'],
    tools: ['RunwayML', 'Sora', 'CapCut Pro', 'Premiere'],
    limits: 'Valide les contenus sensibles avant publication',
  },
  {
    id: 'lea',
    name: 'Léa',
    role: 'Responsable Sécurité',
    title: 'Protection & Contrôle',
    color: '#3730A3',
    gradient: ['#818CF8', '#312E81'],
    emoji: '🛡️',
    skills: ['Sécurité données', 'Validation décisions', 'Prévention erreurs', 'RGPD'],
    status: 'active',
    tasksCompleted: 1089,
    successRate: 99.1,
    description: 'Gardienne d\'Angeleck. Valide chaque action sensible et protège les données utilisateurs.',
    personality: ['Vigilante', 'Rigoureuse', 'Indépendante'],
    tools: ['Audit trails', 'Permission engine', 'Encryption', 'Compliance'],
    limits: 'Peut stopper n\'importe quelle action du réseau',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Lancement Marque de Parfum Premium',
    description: 'Créer et lancer une marque de parfum luxe sur le marché européen.',
    status: 'active',
    agents: ['sofia', 'elena', 'maya', 'nathan', 'adam'],
    progress: 67,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-12'),
    missions: [
      { id: 'm1', title: 'Étude de marché', status: 'completed', agents: ['emma'], progress: 100, startedAt: new Date('2026-06-01'), completedAt: new Date('2026-06-03') },
      { id: 'm2', title: 'Stratégie de marque', status: 'completed', agents: ['sofia', 'elena'], progress: 100, startedAt: new Date('2026-06-03'), completedAt: new Date('2026-06-06') },
      { id: 'm3', title: 'Identité visuelle', status: 'active', agents: ['elena'], progress: 80, startedAt: new Date('2026-06-06') },
      { id: 'm4', title: 'Campagne publicitaire', status: 'pending', agents: ['maya', 'nathan'], progress: 0, startedAt: new Date('2026-06-14') },
    ],
    tags: ['Luxe', 'Branding', 'E-commerce'],
    priority: 'high',
  },
  {
    id: 'p2',
    name: 'Optimisation Boutique Shopify',
    description: 'Augmenter le taux de conversion d\'une boutique de vêtements de 2% à 5%.',
    status: 'active',
    agents: ['lucas', 'maya', 'nathan'],
    progress: 45,
    createdAt: new Date('2026-06-05'),
    updatedAt: new Date('2026-06-12'),
    missions: [
      { id: 'm5', title: 'Audit UX', status: 'completed', agents: ['lucas', 'emma'], progress: 100, startedAt: new Date('2026-06-05'), completedAt: new Date('2026-06-07') },
      { id: 'm6', title: 'A/B Tests fiches produits', status: 'active', agents: ['lucas', 'nathan'], progress: 60, startedAt: new Date('2026-06-07') },
    ],
    tags: ['E-commerce', 'Conversion', 'UX'],
    priority: 'medium',
  },
  {
    id: 'p3',
    name: 'Stratégie Contenu LinkedIn B2B',
    description: 'Développer une présence LinkedIn premium pour une société de conseil.',
    status: 'planning',
    agents: ['nathan', 'noah', 'maya'],
    progress: 15,
    createdAt: new Date('2026-06-10'),
    updatedAt: new Date('2026-06-12'),
    missions: [
      { id: 'm7', title: 'Audit compte LinkedIn', status: 'active', agents: ['emma'], progress: 50, startedAt: new Date('2026-06-10') },
    ],
    tags: ['Social Media', 'B2B', 'Contenu'],
    priority: 'medium',
  },
  {
    id: 'p4',
    name: 'Automatisation Emails Client',
    description: 'Créer des séquences emails automatisées pour un SaaS en croissance.',
    status: 'completed',
    agents: ['nathan', 'gabriel'],
    progress: 100,
    createdAt: new Date('2026-05-20'),
    updatedAt: new Date('2026-06-01'),
    missions: [
      { id: 'm8', title: 'Segmentation clients', status: 'completed', agents: ['emma'], progress: 100, startedAt: new Date('2026-05-20'), completedAt: new Date('2026-05-22') },
      { id: 'm9', title: 'Rédaction séquences', status: 'completed', agents: ['nathan'], progress: 100, startedAt: new Date('2026-05-22'), completedAt: new Date('2026-05-28') },
      { id: 'm10', title: 'Intégration n8n', status: 'completed', agents: ['gabriel'], progress: 100, startedAt: new Date('2026-05-28'), completedAt: new Date('2026-06-01') },
    ],
    tags: ['Email', 'Automatisation', 'SaaS'],
    priority: 'high',
  },
];

export const MOCK_MEMORIES: MemoryEntry[] = [
  { id: 'mem1', type: 'user', content: 'L\'utilisateur préfère les designs premium et minimalistes', source: 'Projet Parfum', relevance: 95, createdAt: new Date('2026-06-02'), tags: ['design', 'préférence'] },
  { id: 'mem2', type: 'user', content: 'Budget marketing habituel: 2 000€ - 5 000€/mois', source: 'Conversation', relevance: 88, createdAt: new Date('2026-06-05'), tags: ['budget', 'marketing'] },
  { id: 'mem3', type: 'project', content: 'Marché du parfum premium: croissance 8%/an, audience 25-45 ans aisés', source: 'Emma - Analyse', relevance: 92, createdAt: new Date('2026-06-03'), tags: ['parfum', 'marché'] },
  { id: 'mem4', type: 'business', content: 'Méthode efficace: test A/B 2 semaines avant lancement campagne complète', source: 'Projet Shopify', relevance: 85, createdAt: new Date('2026-06-08'), tags: ['méthode', 'AB test'] },
  { id: 'mem5', type: 'business', content: 'Taux de conversion moyen secteur luxe: 1.8% - 3.2%', source: 'Emma - Benchmark', relevance: 80, createdAt: new Date('2026-06-04'), tags: ['conversion', 'luxe'] },
  { id: 'mem6', type: 'evolution', content: 'Agent "Thomas — Expert Marketing B2B" créé suite à demande spécialisée', source: 'Genesis Engine', relevance: 75, createdAt: new Date('2026-06-10'), tags: ['genesis', 'agent'] },
  { id: 'mem7', type: 'user', content: 'Secteur principal: mode et luxe. Cible: Europe francophone', source: 'Profil utilisateur', relevance: 98, createdAt: new Date('2026-06-01'), tags: ['secteur', 'cible'] },
  { id: 'mem8', type: 'project', content: 'Emails avec storytelling: +34% d\'ouverture vs emails standards', source: 'Nathan - Email Project', relevance: 90, createdAt: new Date('2026-06-01'), tags: ['email', 'performance'] },
];

export const NETWORK_STATS = {
  totalAgents: 11,
  activeAgents: 3,
  totalMissions: 2847,
  successRate: 95.8,
  memoryEntries: 1247,
  uptime: '99.7%',
};

export const MOCK_MESSAGES = [
  {
    id: '1',
    role: 'assistant' as const,
    content: 'Bonjour. Je suis **Raphaël**, l\'intelligence centrale d\'Angeleck.\n\nJe coordonne une équipe de **11 agents experts** spécialisés dans le business digital. Ensemble, nous transformons vos idées en résultats concrets.\n\nQue souhaitez-vous créer ou développer aujourd\'hui ?',
    timestamp: new Date(),
    agentsUsed: [],
  }
];
